# frozen_string_literal: true

require "tmpdir"

abort "Linux headers are required" unless RUBY_PLATFORM.include?("linux")

root = File.expand_path("..", __dir__)
values = Dir.mktmpdir do |directory|
  executable = File.join(directory, "dump_constants")
  command = [ENV.fetch("CC", "cc"), "-I#{File.join(root, "ext/mountfd")}",
             File.join(__dir__, "dump_constants.c"), "-o", executable]
  abort "failed to compile constant dumper" unless system(*command)

  IO.popen([executable], &:read)
end

definitions = values.lines(chomp: true).map do |line|
  name, value = line.split("=", 2)
  %(    DEF("#{name}", #{value}ULL);)
end.join("\n")

File.write(File.join(root, "ext/mountfd/constants.c"), <<~C)
  /* Generated by tools/generate_constants.rb from Linux UAPI headers. */
  #include "ruby.h"

  void mountfd_define_constants(VALUE native)
  {
  #define DEF(name, value) rb_define_const(native, name, ULL2NUM(value))
  #{definitions}
  #undef DEF
  }
C
