#include "ruby.h"
#include "compat.h"

void mountfd_define_constants(VALUE native)
{
#ifdef __linux__
# define DEF(name) rb_define_const(native, #name, ULL2NUM(name))
    DEF(FSOPEN_CLOEXEC);
    DEF(FSPICK_CLOEXEC);
    DEF(FSPICK_SYMLINK_NOFOLLOW);
    DEF(FSPICK_NO_AUTOMOUNT);
    DEF(FSPICK_EMPTY_PATH);
    DEF(FSCONFIG_SET_FLAG);
    DEF(FSCONFIG_SET_STRING);
    DEF(FSCONFIG_SET_BINARY);
    DEF(FSCONFIG_SET_PATH);
    DEF(FSCONFIG_SET_PATH_EMPTY);
    DEF(FSCONFIG_SET_FD);
    DEF(FSCONFIG_CMD_CREATE);
    DEF(FSCONFIG_CMD_RECONFIGURE);
    DEF(FSCONFIG_CMD_CREATE_EXCL);
    DEF(FSMOUNT_CLOEXEC);
    DEF(OPEN_TREE_CLONE);
    DEF(OPEN_TREE_CLOEXEC);
    DEF(MOVE_MOUNT_F_SYMLINKS);
    DEF(MOVE_MOUNT_F_AUTOMOUNTS);
    DEF(MOVE_MOUNT_F_EMPTY_PATH);
    DEF(MOVE_MOUNT_T_SYMLINKS);
    DEF(MOVE_MOUNT_T_AUTOMOUNTS);
    DEF(MOVE_MOUNT_T_EMPTY_PATH);
    DEF(MOVE_MOUNT_SET_GROUP);
    DEF(MOVE_MOUNT_BENEATH);
    DEF(MOUNT_ATTR_RDONLY);
    DEF(MOUNT_ATTR_NOSUID);
    DEF(MOUNT_ATTR_NODEV);
    DEF(MOUNT_ATTR_NOEXEC);
    DEF(MOUNT_ATTR__ATIME);
    DEF(MOUNT_ATTR_RELATIME);
    DEF(MOUNT_ATTR_NOATIME);
    DEF(MOUNT_ATTR_STRICTATIME);
    DEF(MOUNT_ATTR_NODIRATIME);
    DEF(MOUNT_ATTR_IDMAP);
    DEF(MOUNT_ATTR_NOSYMFOLLOW);
    DEF(AT_RECURSIVE);
    DEF(AT_EMPTY_PATH);
    DEF(MS_UNBINDABLE);
    DEF(MS_REC);
    DEF(MS_PRIVATE);
    DEF(MS_SLAVE);
    DEF(MS_SHARED);
    DEF(CLONE_NEWNS);
    DEF(CLONE_NEWUSER);
# undef DEF
#else
# define DEF(name, value) rb_define_const(native, name, ULL2NUM(value))
    DEF("FSOPEN_CLOEXEC", 0x1);
    DEF("FSPICK_CLOEXEC", 0x1);
    DEF("FSPICK_SYMLINK_NOFOLLOW", 0x2);
    DEF("FSPICK_NO_AUTOMOUNT", 0x4);
    DEF("FSPICK_EMPTY_PATH", 0x8);
    DEF("FSCONFIG_SET_FLAG", 0);
    DEF("FSCONFIG_SET_STRING", 1);
    DEF("FSCONFIG_SET_BINARY", 2);
    DEF("FSCONFIG_SET_PATH", 3);
    DEF("FSCONFIG_SET_PATH_EMPTY", 4);
    DEF("FSCONFIG_SET_FD", 5);
    DEF("FSCONFIG_CMD_CREATE", 6);
    DEF("FSCONFIG_CMD_RECONFIGURE", 7);
    DEF("FSCONFIG_CMD_CREATE_EXCL", 8);
    DEF("FSMOUNT_CLOEXEC", 0x1);
    DEF("OPEN_TREE_CLONE", 1);
    DEF("OPEN_TREE_CLOEXEC", 0x80000);
    DEF("MOVE_MOUNT_F_SYMLINKS", 0x1);
    DEF("MOVE_MOUNT_F_AUTOMOUNTS", 0x2);
    DEF("MOVE_MOUNT_F_EMPTY_PATH", 0x4);
    DEF("MOVE_MOUNT_T_SYMLINKS", 0x10);
    DEF("MOVE_MOUNT_T_AUTOMOUNTS", 0x20);
    DEF("MOVE_MOUNT_T_EMPTY_PATH", 0x40);
    DEF("MOVE_MOUNT_SET_GROUP", 0x100);
    DEF("MOVE_MOUNT_BENEATH", 0x200);
    DEF("MOUNT_ATTR_RDONLY", 0x1);
    DEF("MOUNT_ATTR_NOSUID", 0x2);
    DEF("MOUNT_ATTR_NODEV", 0x4);
    DEF("MOUNT_ATTR_NOEXEC", 0x8);
    DEF("MOUNT_ATTR__ATIME", 0x70);
    DEF("MOUNT_ATTR_RELATIME", 0);
    DEF("MOUNT_ATTR_NOATIME", 0x10);
    DEF("MOUNT_ATTR_STRICTATIME", 0x20);
    DEF("MOUNT_ATTR_NODIRATIME", 0x80);
    DEF("MOUNT_ATTR_IDMAP", 0x100000);
    DEF("MOUNT_ATTR_NOSYMFOLLOW", 0x200000);
    DEF("AT_RECURSIVE", 0x8000);
    DEF("AT_EMPTY_PATH", 0x1000);
    DEF("MS_UNBINDABLE", 0x20000);
    DEF("MS_REC", 0x4000);
    DEF("MS_PRIVATE", 0x40000);
    DEF("MS_SLAVE", 0x80000);
    DEF("MS_SHARED", 0x100000);
    DEF("CLONE_NEWNS", 0x00020000);
    DEF("CLONE_NEWUSER", 0x10000000);
# undef DEF
#endif
}
